Repository eole-nlp/eole, pull requests merged in 2024-07, with the labels that each got.

#47 [docs] Github Actions workflow to facilitate docs deployment
  .github/workflows/deploy_docs.yml
  .github/workflows/release.yml
Labels: documentation

#51 [fix] Fix paths in wiki_103 recipe, add pyarrow opt requirement
  recipes/wiki_103/prepare_wikitext-103_data.sh
  recipes/wiki_103/wiki_103.yaml
  requirements.opt.txt
Labels: recipes

#53 Add Recipe to train a cometkiwi-like encoder model (which can be used to score sentence pairs)
  recipes/cometkiwi/README.md
  recipes/cometkiwi/added_vocab.txt
  recipes/cometkiwi/combine.sh
  recipes/cometkiwi/cometkiwi-xl-eole.yaml
  recipes/cometkiwi/cometkiwi-xl-inference.yaml
  recipes/cometkiwi/cometkiwi-xxl-eole.yaml
  recipes/cometkiwi/cometkiwi-xxl-inference.yaml
Labels: recipes

#52 Simplify __init__ files, remove some unused code
  eole/__init__.py
  eole/bin/model/extract_embeddings.py
  eole/bin/model/lora_weights.py
  eole/config/__init__.py
  eole/decoders/__init__.py
  eole/decoders/ensemble.py
  eole/encoders/__init__.py
  eole/inputters/__init__.py
  eole/models/__init__.py
  eole/predict/__init__.py
  eole/train_single.py
  eole/utils/loss.py
Labels: refactor

#54 bfloat16 support, and an attempt at homogenizing model_dtype & precision
  docs/docusaurus_tsx/docs/FAQ/precision.md
  eole/bin/convert/convert_HF.py
  eole/bin/convert/convert_T5.py
  eole/bin/convert/convert_falcon.py
  eole/bin/convert/convert_llama.py
  eole/bin/convert/convert_mpt.py
  eole/bin/convert/convert_redpajama.py
  eole/bin/convert/convert_xgen.py
  eole/bin/model/lora_weights.py
  eole/config/__init__.py
  eole/config/common.py
  eole/config/inference.py
  eole/config/training.py
  eole/constants.py
  eole/inputters/dynamic_iterator.py
  eole/models/model.py
  eole/train_single.py
  eole/trainer.py
  eole/utils/loss.py
  eole/utils/optimizers.py
  eole/utils/scoring_utils.py
  recipes/cometkiwi/cometkiwi-xxl-eole.yaml
  recipes/llama2/llama-finetune.yaml
  recipes/mistral/mistral-7b-awq-gemm-inference.yaml
  recipes/wiki_103/wiki_103.yaml
  recipes/wmt17/wmt17_ende.yaml
Labels: enhancement, refactor

#74 Update some FAQ sections
  docs/docusaurus_tsx/docs/FAQ/custom_transforms.md
  docs/docusaurus_tsx/docs/FAQ/pretrained_embeddings.md
  docs/docusaurus_tsx/docs/FAQ/tokenization.md
  docs/docusaurus_tsx/docs/FAQ/transformer.md
  docs/docusaurus_tsx/docs/FAQ/update_vocab.md
Labels: documentation
